create table if not exists public.site_seo_profiles (
  site_id text primary key references public.forms_sites (site_id) on update cascade on delete cascade,
  site_url text not null,
  management_status text not null default 'draft'
    check (management_status in ('draft', 'ready')),
  seo_title text not null default '',
  meta_description text not null default '',
  canonical_url text not null default '',
  robots_directive text not null default 'index, follow',
  language_code text not null default 'en',
  og_title text not null default '',
  og_description text not null default '',
  og_image_url text not null default '',
  twitter_card text not null default 'summary_large_image',
  twitter_title text not null default '',
  twitter_description text not null default '',
  twitter_image_url text not null default '',
  entity_type text not null default 'Organization',
  entity_name text not null default '',
  entity_description text not null default '',
  audience jsonb not null default '[]'::jsonb,
  services jsonb not null default '[]'::jsonb,
  service_areas jsonb not null default '[]'::jsonb,
  search_topics jsonb not null default '[]'::jsonb,
  same_as jsonb not null default '[]'::jsonb,
  faqs jsonb not null default '[]'::jsonb,
  structured_data jsonb not null default '{}'::jsonb,
  llms_summary text not null default '',
  llms_key_facts jsonb not null default '[]'::jsonb,
  ai_crawler_policy jsonb not null default '{}'::jsonb,
  source_snapshot jsonb not null default '{}'::jsonb,
  source_checked_at timestamptz,
  revision integer not null default 1,
  updated_by text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.site_seo_profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'site_seo_profiles'
      and policyname = 'service role manages site seo profiles'
  ) then
    create policy "service role manages site seo profiles"
      on public.site_seo_profiles
      for all
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;
end $$;

insert into public.forms_sites (site_id, site_name, site_key, allowed_origins)
values
  (
    'topfundmanager',
    'Top Fund Manager',
    encode(gen_random_bytes(24), 'hex'),
    '["https://topfundmanager.com","https://www.topfundmanager.com"]'::jsonb
  ),
  (
    'theregurus',
    'The Regurus',
    encode(gen_random_bytes(24), 'hex'),
    '["https://theregurus.com","https://www.theregurus.com"]'::jsonb
  ),
  (
    'nocostnurse',
    'No Cost Nurse',
    encode(gen_random_bytes(24), 'hex'),
    '["https://nocostnurse.com","https://www.nocostnurse.com"]'::jsonb
  ),
  (
    'ghicontractors',
    'GHI Contractors',
    encode(gen_random_bytes(24), 'hex'),
    '["https://ghicontractors.com","https://www.ghicontractors.com"]'::jsonb
  ),
  (
    'jccaring',
    'JC Caring',
    encode(gen_random_bytes(24), 'hex'),
    '["https://jccaring.com","https://www.jccaring.com"]'::jsonb
  ),
  (
    'topfundinjury',
    'Top Fund Injury',
    encode(gen_random_bytes(24), 'hex'),
    '["https://topfundinjury.com","https://www.topfundinjury.com"]'::jsonb
  )
on conflict (site_id) do update
set
  site_name = excluded.site_name,
  allowed_origins = excluded.allowed_origins,
  updated_at = timezone('utc', now());

insert into public.site_seo_profiles (
  site_id,
  site_url,
  management_status,
  seo_title,
  meta_description,
  canonical_url,
  robots_directive,
  language_code,
  og_title,
  og_description,
  og_image_url,
  twitter_card,
  twitter_title,
  twitter_description,
  twitter_image_url,
  entity_type,
  entity_name,
  entity_description,
  audience,
  services,
  service_areas,
  search_topics,
  same_as,
  faqs,
  structured_data,
  llms_summary,
  llms_key_facts,
  ai_crawler_policy,
  source_snapshot,
  source_checked_at
)
values
  (
    'topfundmanager',
    'https://topfundmanager.com/',
    'ready',
    'Real Estate Investing Mentorship & Coaching | Top Fund Manager',
    'Learn real estate investing through Top Fund Manager mentorship, practical education, and one-on-one coaching for residential and commercial deals.',
    'https://topfundmanager.com/',
    'index, follow, max-image-preview:large',
    'en',
    'Real Estate Investing Mentorship | Top Fund Manager',
    'Build practical real estate investing skills through mentorship, education, deal strategy, and one-on-one coaching.',
    'https://topfundmanager.com/assets/images/2023/05/top-fund-manager-slider.jpg',
    'summary_large_image',
    'Real Estate Investing Mentorship | Top Fund Manager',
    'Build practical real estate investing skills through mentorship, education, deal strategy, and one-on-one coaching.',
    'https://topfundmanager.com/assets/images/2023/05/top-fund-manager-slider.jpg',
    'Organization',
    'Top Fund Manager',
    'Top Fund Manager provides real estate investing education and mentorship, including one-on-one coaching on sourcing, financing, renovating, and structuring residential and commercial deals.',
    '["Aspiring real estate investors","Active residential and commercial real estate investors"]'::jsonb,
    '["Real estate investing education","Real estate mentorship","One-on-one real estate coaching","Residential and commercial deal strategy"]'::jsonb,
    '[]'::jsonb,
    '["real estate investing mentorship","real estate investing education","real estate coaching","residential investment strategy","commercial investment strategy"]'::jsonb,
    '[]'::jsonb,
    '[{"question":"What does Top Fund Manager teach?","answer":"Top Fund Manager teaches practical residential and commercial real estate investing strategies, including sourcing, financing, renovating, structuring, and selling deals."},{"question":"Is one-on-one coaching available?","answer":"Yes. Top Fund Manager offers a one-on-one experience alongside its broader mentorship program."}]'::jsonb,
    '{"@context":"https://schema.org","@type":"Organization","@id":"https://topfundmanager.com/#organization","name":"Top Fund Manager","url":"https://topfundmanager.com/","logo":"https://topfundmanager.com/assets/images/2020/12/Top-Fund-Manager-Dark.png","description":"Top Fund Manager provides real estate investing education, mentorship, and one-on-one coaching for residential and commercial investors.","knowsAbout":["Real estate investing","Residential real estate","Commercial real estate","Deal financing","Property renovation","Real estate mentorship"]}'::jsonb,
    'Top Fund Manager is a real estate investing education and mentorship organization. It offers practical training, general mentorship, and one-on-one coaching for people working on residential and commercial investment deals.',
    '["Offers real estate investing mentorship and one-on-one coaching","Covers residential and commercial investment strategies","Teaches sourcing, financing, renovation, deal structure, and portfolio building","Provides a cash-offer inquiry path for property owners"]'::jsonb,
    '{"default":"allow","GPTBot":"allow","OAI-SearchBot":"allow","ChatGPT-User":"allow","ClaudeBot":"allow","PerplexityBot":"allow","Google-Extended":"allow","CCBot":"allow"}'::jsonb,
    '{"final_url":"https://topfundmanager.com/","title":"topfundmanager.com – Real Estate Investing","description":"","canonical":"https://topfundmanager.com/","robots":"max-image-preview:large","og_title":"","og_description":"","og_image":"","schema_types":[]}'::jsonb,
    timezone('utc', now())
  ),
  (
    'theregurus',
    'https://theregurus.com/',
    'ready',
    'Residential & Commercial Real Estate Strategy | The Regurus',
    'The Regurus helps buyers, sellers, tenants, landlords, and investors build residential and commercial real estate strategies tailored to their goals.',
    'https://theregurus.com/',
    'index, follow, max-image-preview:large',
    'en',
    'The Regurus | Residential & Commercial Real Estate Strategy',
    'Get tailored residential and commercial real estate guidance for buying, selling, leasing, property management, and investing.',
    'https://theregurus.com/real-estate-gurus.jpg',
    'summary_large_image',
    'The Regurus | Residential & Commercial Real Estate Strategy',
    'Get tailored residential and commercial real estate guidance for buying, selling, leasing, property management, and investing.',
    'https://theregurus.com/real-estate-gurus.jpg',
    'RealEstateAgent',
    'The Regurus',
    'The Regurus is a full-service residential and commercial real estate partner for buyers, sellers, tenants, landlords, and investors seeking tailored strategy and consulting.',
    '["Home buyers and sellers","Residential and commercial tenants and landlords","Real estate investors"]'::jsonb,
    '["Real estate buying","Real estate selling","Tenant placement","Property management","Real estate investment strategy consulting"]'::jsonb,
    '["Global"]'::jsonb,
    '["residential real estate strategy","commercial real estate consulting","real estate investment strategy","tenant placement","property management"]'::jsonb,
    '["https://www.facebook.com/realestategurus","https://www.linkedin.com/company/realestategurus"]'::jsonb,
    '[{"question":"Who does The Regurus work with?","answer":"The Regurus works with residential and commercial buyers, sellers, tenants, landlords, and investors."},{"question":"What can a strategy session cover?","answer":"A tailored strategy session can cover buying, selling, leasing, property management, and real estate investment goals."}]'::jsonb,
    '{"@context":"https://schema.org","@type":"RealEstateAgent","@id":"https://theregurus.com/#organization","name":"The Regurus","alternateName":"Real Estate Gurus","url":"https://theregurus.com/","logo":"https://theregurus.com/real-estate-gurus.jpg","description":"Residential and commercial real estate consulting for buyers, sellers, tenants, landlords, and investors.","areaServed":"Global","knowsAbout":["Residential real estate","Commercial real estate","Property management","Tenant placement","Real estate investment strategy"],"sameAs":["https://www.facebook.com/realestategurus","https://www.linkedin.com/company/realestategurus"]}'::jsonb,
    'The Regurus, also presented in current site copy as Real Estate Gurus, provides residential and commercial real estate guidance. The team serves buyers, sellers, tenants, landlords, and investors through tailored strategy sessions.',
    '["Provides residential and commercial real estate guidance","Serves buyers, sellers, tenants, landlords, and investors","Offers tailored strategy sessions","Covers buying, selling, tenant placement, property management, and investment strategy"]'::jsonb,
    '{"default":"allow","GPTBot":"allow","OAI-SearchBot":"allow","ChatGPT-User":"allow","ClaudeBot":"allow","PerplexityBot":"allow","Google-Extended":"allow","CCBot":"allow"}'::jsonb,
    '{"final_url":"https://theregurus.com/","title":"Real Estate Gurus | Strategy Inquiry","description":"Real Estate Gurus is your one-stop real estate partner, helping buyers, sellers, tenants, landlords, and investors build winning residential and commercial strategies.","canonical":"https://realestategurus.com/","robots":"index, follow","og_title":"Real Estate Gurus | Strategy Inquiry","og_description":"Partner with Real Estate Gurus for comprehensive residential and commercial real estate guidance backed by winning investment strategies.","og_image":"https://realestategurus.com/real-estate-gurus.jpg","schema_types":["Organization"],"audit_note":"The live theregurus.com page still publishes realestategurus.com canonical and asset URLs; the managed values correct these to theregurus.com."}'::jsonb,
    timezone('utc', now())
  ),
  (
    'nocostnurse',
    'https://nocostnurse.com/',
    'ready',
    'No Cost Nurse | In-Home Nursing Care for Georgia Families',
    'Connecting Georgia families with skilled, Medicaid-approved nurses and CNAs for compassionate in-home care for eligible youth under 21.',
    'https://nocostnurse.com/',
    'index, follow, max-image-preview:large',
    'en',
    'No Cost Nurse | In-Home Nursing Care for Georgia Families',
    'Connecting Georgia families with skilled nurses and CNAs approved by Medicaid for compassionate in-home support for eligible youth under 21.',
    'https://nocostnurse.com/images/social-preview.png',
    'summary_large_image',
    'No Cost Nurse | In-Home Nursing Care for Georgia Families',
    'Connecting Georgia families with skilled nurses and CNAs approved by Medicaid for compassionate in-home support for eligible youth under 21.',
    'https://nocostnurse.com/images/social-preview.png',
    'Organization',
    'No Cost Nurse',
    'No Cost Nurse connects Georgia families of eligible youth under 21 with skilled nurses and CNAs through a Medicaid-focused in-home care referral network.',
    '["Georgia families seeking pediatric in-home nursing","Nurses and CNAs making qualified referrals"]'::jsonb,
    '["Pediatric in-home nursing referrals","Medicaid care eligibility screening","Nurse and CNA referral coordination"]'::jsonb,
    '["Georgia"]'::jsonb,
    '["Georgia pediatric home nursing","Medicaid in-home nursing care","nurse referral network","in-home care for youth under 21"]'::jsonb,
    '[]'::jsonb,
    '[{"question":"Who may qualify for care through No Cost Nurse?","answer":"Georgia youth under 21 with qualifying medical needs and Medicaid coverage may be eligible. The care provider reviews each referral and confirms eligibility."},{"question":"What happens after a referral is submitted?","answer":"The team reviews the information and typically reaches out within one to two business days to discuss the referral and next steps."}]'::jsonb,
    '{"@context":"https://schema.org","@type":"Organization","@id":"https://nocostnurse.com/#organization","name":"No Cost Nurse","url":"https://nocostnurse.com/","logo":"https://nocostnurse.com/images/nurse_logo_v3_transparent.png","description":"A Georgia-focused referral network connecting eligible families with skilled in-home nurses and CNAs.","areaServed":{"@type":"State","name":"Georgia"},"knowsAbout":["Pediatric home nursing","Georgia Medicaid","Nurse referrals","In-home care"]}'::jsonb,
    'No Cost Nurse is a Georgia-focused referral network for families seeking skilled in-home nursing for eligible youth under 21. It helps collect eligibility information and connect families with Medicaid-approved nurses and CNAs.',
    '["Focused on Georgia families","Supports eligible youth under age 21","Connects families with skilled nurses and CNAs","Uses a referral and eligibility review process","Staff typically follows up within one to two business days"]'::jsonb,
    '{"default":"allow","GPTBot":"allow","OAI-SearchBot":"allow","ChatGPT-User":"allow","ClaudeBot":"allow","PerplexityBot":"allow","Google-Extended":"allow","CCBot":"allow"}'::jsonb,
    '{"final_url":"https://nocostnurse.com/","title":"No Cost Nurse | In-Home Nursing Care for Georgia Families","description":"Connecting Georgia families with skilled, Medicaid-approved nurses and CNAs. Specialized in-home nursing care for youth under 21. Verified care you can trust.","canonical":"https://nocostnurse.com/","robots":"index, follow","og_title":"No Cost Nurse | In-Home Nursing Care for Georgia Families","og_description":"Connecting families with skilled nurses and CNAs approved by Medicaid. Georgia-focused, compassionate in-home support for youth under 21.","og_image":"https://nocostnurse.com/images/social-preview.png","schema_types":["Organization"]}'::jsonb,
    timezone('utc', now())
  ),
  (
    'ghicontractors',
    'https://ghicontractors.com/',
    'ready',
    'GHI Contractors | Roofing & Home Improvement in Metro Atlanta',
    'GHI Contractors provides roofing, flooring, tile, cabinet, and countertop services across Metro Atlanta. Request a free estimate at 404-771-1611.',
    'https://ghicontractors.com/',
    'index, follow, max-image-preview:large',
    'en',
    'GHI Contractors | Roofing & Home Improvement in Metro Atlanta',
    'Expert roofing, flooring, tile, cabinet, and countertop services for homeowners across Metro Atlanta.',
    'https://ghicontractors.com/images/og-image.jpg',
    'summary_large_image',
    'GHI Contractors | Roofing & Home Improvement in Metro Atlanta',
    'Expert roofing, flooring, tile, cabinet, and countertop services for homeowners across Metro Atlanta.',
    'https://ghicontractors.com/images/og-image.jpg',
    'HomeAndConstructionBusiness',
    'GHI Contractors',
    'GHI Contractors is a licensed and insured Metro Atlanta home-improvement company providing roofing, flooring, tile, cabinet, and countertop services with free estimates.',
    '["Homeowners and property owners in Metro Atlanta"]'::jsonb,
    '["Roofing","Flooring","Tile installation","Cabinets","Countertops"]'::jsonb,
    '["Metro Atlanta","Fulton County, Georgia","DeKalb County, Georgia","Gwinnett County, Georgia","Newton County, Georgia","Rockdale County, Georgia","Clayton County, Georgia","Cobb County, Georgia"]'::jsonb,
    '["Metro Atlanta roofing contractor","Atlanta flooring contractor","tile installation Atlanta","cabinet installation Atlanta","countertop installation Atlanta","home improvement contractor"]'::jsonb,
    '["https://www.facebook.com/GHIContractors","https://www.instagram.com/ghicontractors"]'::jsonb,
    '[{"question":"What services does GHI Contractors provide?","answer":"GHI Contractors provides roofing, flooring, tile, cabinet, and countertop services."},{"question":"Where does GHI Contractors work?","answer":"GHI Contractors serves Metro Atlanta, including communities across Fulton, DeKalb, Gwinnett, Newton, Rockdale, Clayton, and Cobb counties."},{"question":"Does GHI Contractors offer estimates?","answer":"Yes. GHI Contractors offers free estimates for home-improvement projects."}]'::jsonb,
    '{"@context":"https://schema.org","@type":"HomeAndConstructionBusiness","@id":"https://ghicontractors.com/#business","name":"GHI Contractors","url":"https://ghicontractors.com/","image":"https://ghicontractors.com/images/og-image.jpg","telephone":"404-771-1611","email":"service@ghicontractors.com","description":"Roofing, flooring, tile, cabinet, and countertop services in Metro Atlanta.","address":{"@type":"PostalAddress","addressRegion":"GA","addressCountry":"US"},"areaServed":["Metro Atlanta","Fulton County, GA","DeKalb County, GA","Gwinnett County, GA","Newton County, GA","Rockdale County, GA","Clayton County, GA","Cobb County, GA"],"priceRange":"$$","sameAs":["https://www.facebook.com/GHIContractors","https://www.instagram.com/ghicontractors"]}'::jsonb,
    'GHI Contractors is a Metro Atlanta home-improvement contractor offering roofing, flooring, tile, cabinets, and countertops. The company serves homeowners across multiple Atlanta-area counties and offers free estimates.',
    '["Provides roofing, flooring, tile, cabinet, and countertop services","Serves Metro Atlanta and surrounding counties","Published site identifies the business as licensed and insured","Offers free estimates","Phone: 404-771-1611"]'::jsonb,
    '{"default":"allow","GPTBot":"allow","OAI-SearchBot":"allow","ChatGPT-User":"allow","ClaudeBot":"allow","PerplexityBot":"allow","Google-Extended":"allow","CCBot":"allow"}'::jsonb,
    '{"final_url":"https://ghicontractors.com/","title":"GHI Contractors | Roofing, Flooring & Home Improvement in Metro Atlanta","description":"GHI Contractors provides expert roofing, flooring, tile, cabinet, and countertop services in Metro Atlanta. Serving Fulton, DeKalb, Gwinnett, and surrounding counties. Call 404-771-1611 for a free estimate.","canonical":"https://ghicontractors.com","robots":"index, follow","og_title":"GHI Contractors | Roofing, Flooring & Home Improvement in Metro Atlanta","og_description":"Expert roofing, flooring, tile, cabinet, and countertop services in Metro Atlanta. Quality craftsmanship you can trust.","og_image":"https://ghicontractors.com/images/og-image.jpg","schema_types":["HomeAndConstructionBusiness"]}'::jsonb,
    timezone('utc', now())
  ),
  (
    'jccaring',
    'https://jccaring.com/',
    'ready',
    'Free Pediatric Home Nursing in Atlanta | JC Caring',
    'JC Caring provides in-home nursing for medically fragile children under 21 covered by Georgia Medicaid, serving families across Metro Atlanta.',
    'https://jccaring.com/',
    'index, follow, max-image-preview:large',
    'en',
    'Free Pediatric Home Nursing for Georgia Medicaid Families | JC Caring',
    'Compassionate in-home nursing for medically fragile children under 21, covered by Georgia Medicaid and serving Metro Atlanta families.',
    'https://jccaring.com/images/logo-text.png',
    'summary_large_image',
    'Free Pediatric Home Nursing for Georgia Medicaid Families | JC Caring',
    'Compassionate in-home nursing for medically fragile children under 21, covered by Georgia Medicaid and serving Metro Atlanta families.',
    'https://jccaring.com/images/logo-text.png',
    'MedicalBusiness',
    'JC Caring Home Services',
    'JC Caring Home Services provides professional in-home nursing for medically fragile children under 21 whose services are covered by Georgia Medicaid, including skilled nursing and complex-care support.',
    '["Georgia Medicaid families with medically fragile children under 21","Pediatric home-health nurses and caregivers"]'::jsonb,
    '["Pediatric skilled nursing","Respiratory support","Personal care","Therapy coordination","Nutrition and feeding-tube care","Medication management","Parent caregiver support"]'::jsonb,
    '["Metro Atlanta","Georgia"]'::jsonb,
    '["pediatric home nursing Atlanta","Georgia Medicaid pediatric nursing","GAPP nursing care","tracheostomy care at home","ventilator support at home","medically fragile children home care"]'::jsonb,
    '[]'::jsonb,
    '[{"question":"Who does JC Caring serve?","answer":"JC Caring serves medically fragile children under 21 and their families across Metro Atlanta and Georgia."},{"question":"How are JC Caring services paid for?","answer":"For eligible children, services are covered by Georgia Medicaid at no cost to the family."},{"question":"What types of care are available?","answer":"Services include skilled nursing, respiratory support, personal care, therapy coordination, nutrition and feeding-tube care, and medication management."}]'::jsonb,
    '{"@context":"https://schema.org","@type":"MedicalBusiness","@id":"https://jccaring.com/#business","name":"JC Caring Home Services","alternateName":"JC Caring","url":"https://jccaring.com/","logo":"https://jccaring.com/images/logo.png","telephone":"(678) 823-5817","description":"Pediatric home nursing services for medically fragile children covered by Georgia Medicaid.","address":{"@type":"PostalAddress","addressLocality":"Atlanta","addressRegion":"GA","addressCountry":"US"},"areaServed":{"@type":"GeoCircle","geoMidpoint":{"@type":"GeoCoordinates","latitude":33.749,"longitude":-84.388},"geoRadius":"50 mi"},"medicalSpecialty":"Pediatric Home Health Care","priceRange":"Free for Medicaid-eligible patients"}'::jsonb,
    'JC Caring Home Services provides pediatric home nursing for medically fragile children under 21 in Georgia. Eligible services are covered by Georgia Medicaid. The team supports complex needs including respiratory, skilled nursing, personal care, feeding, therapy coordination, and medication management.',
    '["Serves medically fragile children under age 21","Eligible services are covered by Georgia Medicaid","Serves Metro Atlanta and Georgia families","Provides skilled pediatric nursing and complex-care support","Phone: (678) 823-5817"]'::jsonb,
    '{"default":"allow","GPTBot":"allow","OAI-SearchBot":"allow","ChatGPT-User":"allow","ClaudeBot":"allow","PerplexityBot":"allow","Google-Extended":"allow","CCBot":"allow"}'::jsonb,
    '{"final_url":"https://jccaring.com/","title":"Free Pediatric Home Nursing for Medicaid Children in Atlanta | JC Caring Home Services","description":"JC Caring provides FREE in-home nursing care for medically fragile children under 21 covered by Georgia Medicaid. Trach care, ventilator support, G-tube feeding & more. Serving metro Atlanta.","canonical":"https://jccaringhomeservices.com/","robots":"index, follow","og_title":"Free Pediatric Home Nursing for Medicaid Children | JC Caring","og_description":"Professional in-home nursing services for medically fragile children at no cost to Georgia Medicaid families. Serving the Atlanta metro area.","og_image":"","schema_types":["MedicalBusiness"],"audit_note":"The live jccaring.com page still publishes jccaringhomeservices.com canonical and structured-data URLs; the managed values correct these to jccaring.com."}'::jsonb,
    timezone('utc', now())
  ),
  (
    'topfundinjury',
    'https://topfundinjury.com/',
    'ready',
    'Personal Injury Attorney Matching | Top Fund Injury',
    'Top Fund Injury connects accident victims nationwide with trial-ready personal injury attorneys. Get a free, confidential case evaluation 24/7.',
    'https://topfundinjury.com/en',
    'index, follow, max-image-preview:large',
    'en',
    'Top Fund Injury | Personal Injury Attorney Matching',
    'Connect with a personal injury attorney for a free, confidential case evaluation. No upfront costs, and fees apply only if you win.',
    'https://topfundinjury.com/top-fund-injury-maximum-compensation.png',
    'summary_large_image',
    'Top Fund Injury | Personal Injury Attorney Matching',
    'Connect with a personal injury attorney for a free, confidential case evaluation. No upfront costs, and fees apply only if you win.',
    'https://topfundinjury.com/top-fund-injury-maximum-compensation.png',
    'Organization',
    'Top Fund Injury',
    'Top Fund Injury is a nationwide attorney-matching service that connects accident victims with personal injury lawyers for free, confidential case evaluations.',
    '["People injured in accidents who are seeking legal representation"]'::jsonb,
    '["Personal injury attorney matching","Free case evaluation","Accident case intake","Legal and medical referral coordination"]'::jsonb,
    '["United States"]'::jsonb,
    '["personal injury attorney matching","free injury case evaluation","car accident lawyer referral","truck accident attorney","nationwide injury attorney"]'::jsonb,
    '[]'::jsonb,
    '[{"question":"What does Top Fund Injury do?","answer":"Top Fund Injury connects accident victims with attorneys who handle their type of personal injury case."},{"question":"Does a case evaluation cost anything?","answer":"No. The initial case evaluation is free and confidential, with no upfront legal costs."},{"question":"When is help available?","answer":"Top Fund Injury accepts case inquiries 24 hours a day, seven days a week."}]'::jsonb,
    '{"@context":"https://schema.org","@type":"Organization","@id":"https://topfundinjury.com/#organization","name":"Top Fund Injury","url":"https://topfundinjury.com/","image":"https://topfundinjury.com/top-fund-injury-maximum-compensation.png","description":"A nationwide attorney-matching service for accident victims seeking personal injury representation.","areaServed":{"@type":"Country","name":"United States"},"availableLanguage":["English","Spanish"],"knowsAbout":["Personal injury law","Car accidents","Truck accidents","Premises liability","Attorney matching"]}'::jsonb,
    'Top Fund Injury is a nationwide personal injury attorney-matching service. It offers free, confidential case evaluations and connects accident victims with attorneys based on case type. There are no upfront legal costs, and attorney fees apply only when a case is won.',
    '["Nationwide personal injury attorney matching","Free and confidential case evaluation","Available 24/7","No upfront legal costs","Supports multiple accident and injury case types","Past results do not guarantee future outcomes"]'::jsonb,
    '{"default":"allow","GPTBot":"allow","OAI-SearchBot":"allow","ChatGPT-User":"allow","ClaudeBot":"allow","PerplexityBot":"allow","Google-Extended":"allow","CCBot":"allow"}'::jsonb,
    '{"final_url":"https://topfundinjury.com/en","title":"Top Fund Injury — Maximum Compensation","description":"Top Fund Injury connects accident victims with experienced attorneys who fight for maximum compensation. Free case evaluation, available 24/7.","canonical":"https://topfundinjury.com/en","robots":"","og_title":"Top Fund Injury — Maximum Compensation","og_description":"Top Fund Injury connects accident victims with experienced attorneys who fight for maximum compensation. Free case evaluation, available 24/7.","og_image":"","schema_types":[]}'::jsonb,
    timezone('utc', now())
  )
on conflict (site_id) do nothing;
